#!/usr/bin/env bash
set -euo pipefail

# pick GPU
export CUDA_VISIBLE_DEVICES=0
export CUDA_LAUNCH_BLOCKING=1

# Global configs
DATASET_NAME="rel-ratebeer"
OUTPUT_ROOT="outputs"
TASK_NAME="user-churn" # "user-badge", "user-engagement", "post-votes", "driver-dnf", "driver-top3", "driver-position"
TASK_KIND="classification" #regression #classification
NUM_LAYERS=3

EPOCHS=20
# BATCH_SIZE=512
# BATCH_SIZE=256
BATCH_SIZE=128
TEXT_EMB_BATCH_SIZE=256
EARLY_STOP_PATIENCE=10
MAX_STEPS_PER_EPOCH=1500

FANOUT=64
MODEL_TYPE="hgt"   # "hgs" or "hgt" (hgs: HeteroGraphSAGE, hgt: Heterogeneous Graph Transformer)
ATTENTION_HEAD=4 # Only applicable for HGT


# pruning config (leave empty for random fanout)
# All the pruning configs can be found inside the respective task folder under ./outputs/rel-datasetname

# ./outputs/rel-ratebeer/user-churn/user_churn_3hops.py (pruning config generated using MPS-GNN)
SAMPLING_CFG_PATH="./outputs/rel-ratebeer/user-churn/user_churn_pruned_3hops_0.1.json"  # Pruning config generated by MetaSieve for the user

python train_stepwise.py \
  --device cuda:0 \
  --dataset_name "$DATASET_NAME" \
  --output_root "$OUTPUT_ROOT" \
  --task_name "$TASK_NAME" \
  --task_kind "$TASK_KIND" \
  --num_layers "$NUM_LAYERS" \
  --epochs "$EPOCHS" \
  --batch_size "$BATCH_SIZE" \
  --text_emb_batch_size "$TEXT_EMB_BATCH_SIZE" \
  --early_stop_patience "$EARLY_STOP_PATIENCE" \
  --max_steps_per_epoch "$MAX_STEPS_PER_EPOCH" \
  --fanout "$FANOUT" \
  --heads "$ATTENTION_HEAD"\
  --model_type "$MODEL_TYPE" \
  ${SAMPLING_CFG_PATH:+--sampling_cfg_path "$SAMPLING_CFG_PATH"}
